version: "3.9"

services:
  db:
    container_name: mail_database
    image: postgres
    restart: always
    ports:
      - 5432:5432
      - 5433:5433
    environment:
      DB_NAME: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    links:
      - "db:mail_database"
    container_name: mail_adminer
    image: adminer
    restart: always
    environment:
      host: $DB_HOST
    ports:
      - 8080:8080

  tgbot:
    links:
      - "db:mail_database"
    container_name: mail_bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
    volumes:
      - static-files:/var/lib/data/static

volumes:
  db-data:
  static-files:
